### ISSUE TITLE
Require tinc 

### ISSUE THREAD

**Issue by cornelinux** [NetKnights-GmbH/privacyidea-appliance#45]
1. we need to require tinc when installing the pi-appliance
2. we need to check if tinc is installed on the remote privacyIDEA system

**Comment by cornelinux** [comment]
@fredreichbier can you please enhance the check for the remote system?
I will take care for the requirement.

**Comment by fredreichbier** [comment]
Currently, the tinc setup is optional. The user is asked if a tinc tunnel should be set up between the hosts.

Should we remove the possibility of unencrypted communication between the MySQL peers and always set up a tinc tunnel between the hosts?

**Comment by cornelinux** [comment]
I would not do this.
Two machines could be located in a trusted subnet.
And then it might be more difficult to find an additional transfer net.

Don't get me wrong. I would always set up with the tinc tunnel. 
But I think reality looks different.

**Comment by fredreichbier** [comment]
Sounds good :) So *if* the user wants to set up an encrypted tinc tunnel, we should check for tinc on the remote system.

**Comment by cornelinux** [comment]
Oh, I think the original intention was to add tinc as a  requirement to the appliance package.
But as node 1 could have the enterprise edition and node 2 the comm7nitz edition it could still be, that node 2 has no tinc.
So yes, checking it would be great.
