### ISSUE TITLE
Add deletion of old backup files

### ISSUE THREAD

**Issue by cornelinux** [NetKnights-GmbH/privacyidea-appliance#53]
the pi-appliance should add the deletion of old backup files.
In the ui the admin should use the number of days.
Then we can use "find" to delete these files.

**Comment by cornelinux** [comment]
Hi @fredreichbier 
can you please take care about this?
I think it is ok to run the *find-and-delete* task once  a day as a cron job. This does not need to be configured when and how often. 
The only thing the user can set in the UI would be to define how many days should be kept.

**Comment by fredreichbier** [comment]
Hm, don't we already have this? "Backup and Restore" -> "Set backup rotation" allows to set a number of days. If I enter 10 days, the following cronjob is added to the crontab:
```
0	2	*	*	*	root	find /var/lib/privacyidea/backup -atime +10 -delete
```

**Comment by cornelinux** [comment]
Oh you are right. 
This is cool!

**Comment by fredreichbier** [comment]
Next-level agile software development :-)

**Comment by cornelinux** [comment]
So we close it, right?
