### ISSUE TITLE
copy freeradius during setup of redundancy

### ISSUE THREAD

**Issue by cornelinux** [NetKnights-GmbH/privacyidea-appliance#55]
When setting up the redundancy it would be great, if the freeradius configuration would also be copied to the other machine.

The setup wizard UI can ask, if the freeradius dir should also be copied to the remote machine.

At least we would only have to adapt the clients.conf.

**Comment by fredreichbier** [comment]
Then, we should also check during redundancy setup that the ``privacyidea-radius`` package is installed on the remote machine, I think?

Also, we should not only copy the ``/etc/freeradius`` directory, but also the file ``/etc/privacyidea/rlm_perl.ini``.

**Comment by fredreichbier** [comment]
We should copy the ``/etc/freeradius`` directory, but need to take special care with two subdirectories:
* ``certs/`` contains certificates that are generated during setup and should not be copied
* ``sites-enabled/`` contains symlinks to files in ``sites-available/``.
