### ISSUE TITLE
Update Ubuntu appliance packages to work with privacyIDEA 3.0

### ISSUE THREAD

**Issue by fredreichbier** [NetKnights-GmbH/privacyidea-appliance#56]
We need to find a way to make the appliance Ubuntu packages work with privacyIDEA 3.0:

The appliance imports code from the Python package ``privacyidea``. But with the new Ubuntu packages, the package is not globally available anymore, only in a virtualenv.

This leads to the following error:

```
# pi-appliance
Traceback (most recent call last):
  File "/mnt/venv/bin/pi-appliance", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/mnt/privacyidea-appliance/authappliance/pi-appliance", line 20, in <module>
    from authappliance.menu import main
  File "/mnt/privacyidea-appliance/authappliance/menu.py", line 38, in <module>
    from privacyidea.lib.auth import (create_db_admin, get_db_admins,
ImportError: No module named privacyidea.lib.auth
```

We could
* install the appliance in the same virtualenv as privacyIDEA
* install the appliance in a separate virtualenv, with a separate installation of the privacyIDEA package

**Comment by fredreichbier** [comment]
As another alternative, we could install the appliance system-wide (as we already do), and manually add the privacyIDEA virtualenv path to the search path for Python modules before importing:
```python
import sys
sys.path.append('/opt/privacyidea/lib/python2.7/site-packages')
from privacyidea.lib.auth import create_db_admin
```

**Comment by cornelinux** [comment]
This sounds as if we could also install the appliance in a virtualenv ``/opt/piappliance/`` and add the path as mentioned above.

The debian package would simply add a link

    ln -s /opt/piappliance/bin/pi-appliance /usr/local/bin/

I think using a also here virtualenv gives us a more stable environment. As the appliance will only work with a dedicated privacyIDEA installation it might be ok to reference the other virtualenv.
@fredreichbier what do you think?

**Comment by fredreichbier** [comment]
I opened #73. With this PR, the appliance tries to import ``privacyidea`` from the local virtualenv (which will work for users who manually install privacyIDEA and the appliance in the same virtualenv), and uses ``/opt/privacyidea/lib/python2.7/site-packages`` as a fall-back search path (in case of the distribution packages).

If we merge this into the appliance code, we can build distribution packages without the need to put .pth files anywhere, and without the need to include patch files in the distribution packages. What do you think?

**Comment by fredreichbier** [comment]
We have a problem with the automatic update cronjob, which adds the following line to ``/etc/crontab``:
```
30	*	*	*	*	root	/usr/bin/pi-appliance-update -t security -b -c
```
but ``pi-appliance-update`` is not visible outside of the virtualenv. We could ...
* add a symlink to ``pi-appliance-update`` like we do for ``pi-appliance`` and ``pi-manage``
* modify the crontab line such that it points to ``/opt/appliance/bin/pi-appliance-update`` (or so). In order to make this work for manual appliance installations as well (which might not be in ``/opt/appliance``), we can probably use some setuptools function to find out the exact location of the ``pi-appliance-update`` script.

**Comment by cornelinux** [comment]
I would prefer a symlink.
The question is, if we should link to /usr/bin/pi-appaliance-update or to /usr/local/bin.

The pi-manage is linked to /usr/local/bin...

**Comment by plettich** [comment]
I would prefer the symlink as well, and `/usr/local/bin`. Maybe we can track this during installation and set the correct path when writing the cronjob.

**Comment by fredreichbier** [comment]
I think a symlink sounds good and ``/usr/local/bin`` sounds like the best place to put it.

Could we maybe just write ``pi-appliance-update`` to the crontab, without any absolute path?

But we then need to take care of users migrating from Appliance 2.0, because they have ``/usr/bin/pi-appliance-update`` in their crontab. After the update, the cronjob will not run anymore, and the appliance code does not currently recognize it as an update cronjob :-/
https://github.com/NetKnights-GmbH/privacyidea-appliance/blob/bf3881693ff9a52086fe4d8bb8e44641cbd7fd44/authappliance/lib/updates.py#L67

**Comment by cornelinux** [comment]
I am not sure, but I think commands without absolute path's are a bad idea in crontab?

**Comment by plettich** [comment]
> I am not sure, but I think commands without absolute path's are a bad idea in crontab?

especially since `/usr/local/bin` is not in the default crontab `$PATH`

**Comment by fredreichbier** [comment]
No idea about the best practices, but do currently write ``pi-manage`` calls without absolute paths to the crontab:
```
5	*	*	*	*	privacyidea	pi-manage backup create -d /var/lib/privacyidea/backup
```
And don't ask me why, but the ``PATH`` from ``/etc/crontab`` does contain ``/usr/local/bin`` on my Ubuntu 16.04 :)
```
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
```

**Comment by cornelinux** [comment]
This looks evil.

**Comment by fredreichbier** [comment]
Hm, I just checked: The Ubuntu 16.04 [cron package](https://packages.ubuntu.com/xenial/cron) contains the following ``/etc/crontab`` whose PATH includes ``/usr/local/bin/``:

```
# /etc/crontab: system-wide crontab
# Unlike any other crontab you don't have to run the `crontab'
# command to install the new version when you edit this file
# and files in /etc/cron.d. These files also have username fields,
# that none of the other crontabs do.

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# m h dom mon dow user	command
17 *	* * *	root    cd / && run-parts --report /etc/cron.hourly
25 6	* * *	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
47 6	* * 7	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )
52 6	1 * *	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.monthly )
#
```

Regarding the ``pi-appliance-update`` issue above, I think we have at least the following options:

1) The appliance package symlinks ``/usr/bin/pi-appliance-update`` to to the virtualenv script.  Then we don't have to worry about existing users migrating, because the cronjobs will continue to work just fine. But we put a file in ``/usr/bin/``, which is not nice.
2) The appliance package symlinks ``/usr/local/bin/pi-appliance-update`` to the virtualenv script. Then we need to think about existing users migrating:
  * the old cronjob will stop working because it uses the absolute path ``/usr/bin/pi-appliance-update``
  * the appliance code currently expects command lines of update jobs to start with ``/usr/bin/pi-appliance-update``, so we'd need to adjust the code a bit

Option 1) is not very nice because we put a file in /usr/bin, but overall it seems more robust to me.

**Comment by plettich** [comment]
Well, the manpage states 
> PATH  is  set  to  "/usr/bin:/bin"

so I guess they didn't update the manpage :-)

**Comment by fredreichbier** [comment]
Closing this issue, as this has been taken care of in https://github.com/NetKnights-GmbH/ubuntu/
