### ISSUE TITLE
Support FreeRADIUS 3 on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by fredreichbier** [NetKnights-GmbH/privacyidea-appliance#66]
Right now, the appliance tool relies on the existence of ``/etc/freeradius/clients.conf``:
https://github.com/NetKnights-GmbH/privacyidea-appliance/blob/eedc27d6392da1d79147226c4b1e2f15f54a46a1/authappliance/lib/appliance.py#L373

But this file doesn't exist on Ubuntu 18.04 LTS which ships FreeRADIUS 3 (see #61).
We should check how much effort is needed to support FreeRADIUS 3.

**Comment by cornelinux** [comment]
The config file is tried to be read [here](https://github.com/NetKnights-GmbH/privacyidea-appliance/blob/master/authappliance/menu.py#L1319), it is set to None and [later ](https://github.com/NetKnights-GmbH/privacyidea-appliance/blob/master/authappliance/menu.py#L1326) the Menu is not displayed. 

This actually does not disturb the ``pi-appliance``. It runs nicely on Ubuntu 18.04, the FreeRADIUS entry is simply missing.
@plettich I checked several functionalities with Python 3.6 on Ubuntu 18.04 and everything works out fine. Have not checked mysql master-master, yet.

For the next release on Ubuntu 18.04 and python 3 we should be able to identify, wheather radius is contained in ``/etc/freeradius`` or ``/etc/freeradius/3.0``. The parsers work very much the same, then.

**Comment by cornelinux** [comment]
We could start by adapting ``menu.py`` like this:

~~~~python
class RadiusMenu(object):

    def __init__(self, app, dialog):
        self.app = app
        self.d = dialog
        try:
            if os.path.exists("/etc/freeradius/3.0/clients.conf"):
                self.RadiusConfig = FreeRADIUSConfig("/etc/freeradius/3.0/clients.conf")
            else:
                self.RadiusConfig = FreeRADIUSConfig()
        except:
            # No Radius Server available
            self.RadiusConfig = None
~~~~

But the default ``clients.conf`` of FreeRADIUS 3.0 contains ``limit`` sections, that are currently not supported in the freeradiusparser.

**Comment by plettich** [comment]
Getting the `limit` section recognized by the parser is quite simple but we need to add it to the [`format()`](https://github.com/privacyidea/freeradiusparser/blob/356a4fb20d55df8ce2ae6b4a9c331caa795f8eb4/freeradiusparser.py#L104) function to be able to write out a correct `clients.conf` file.
