### ISSUE TITLE
Cronjobs do not support forward-slash notation

### ISSUE THREAD

**Issue by fredreichbier** [NetKnights-GmbH/privacyidea-appliance#74]
Steps to reproduce:
1) add an audit rotation cronjob that should be run at ``*/5 * * * *``, i.e. every 5 minutes
2) the cronjob is correctly written to ``/etc/crontab``
3) add an arbitrary backup cronjob
4) notice that the audit rotation cronjob is gone from ``/etc/crontab``

This is because crontabparser does not support the forward-slash notation. Hence, it ignores the corresponding line when parsing ``/etc/crontab`` in step 3, and the crontab written in step 4 misses this line.

**Comment by cornelinux** [comment]
Then, this should be a bug [here](https://github.com/privacyidea/crontabparser), right?

**Comment by fredreichbier** [comment]
Hm, possibly. I opened https://github.com/privacyidea/crontabparser/issues/3. I'd like to keep this issue here open as well, because the bug negatively affects the functionality of the appliance.
