### ISSUE TITLE
broken lines in window borders

### ISSUE THREAD

**Issue by cornelinux** [NetKnights-GmbH/privacyidea-appliance#81]
The dialogs of the pi-appliance do not have nicely lined dialog windows in a putty session on a windows machine, but instead wrong characters. How can we fix the window borders?

See https://askubuntu.com/questions/16912/ncurses-prompts-look-broken-in-putty-from-windows

It seems a putty setting.
Should we add this to the documentation or add a welcome dialog, that tells the user, how to configure his putty?
Or add an extra "putty help" menu?
@plettich what do you think?

**Comment by plettich** [comment]
Had the same issue in Linux, fixed it by restarting the terminal...
It does seem to be an UTF8/font-issue. I'll look into it.

**Comment by plettich** [comment]
Actually `export NCURSES_NO_UTF8_ACS=1` works in my setup, so maybe we can set this when starting the appliance (I'll check it out).
A relatively easy putty setting is described here: https://stackoverflow.com/a/26426723/7036742

**Comment by cornelinux** [comment]
Would be cool if we could do it on appliance level and not need to reconfigure putty.
